/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      fontFamily: {
        inter: ["var(--font-inter)"],
        montserrat: ["var(--font-montserrat)"],
      },
      fontSize: {
        sm: ["0.75rem", "1rem"],
        md: ["0.875rem", "1.375rem"],
        lg: ["1rem", "1.5rem"],
        xl: ["1.25rem", "1.75rem"],
        "2xl": ["1.5rem", "2rem"],
        "3xl": ["2rem", "2.5rem"],
      },
      colors: {
        blue: "#18489A",
        hoverBlue: "#ECF0F7",
        pressedBlue: "#E2E8F2",
        purple: "#9747FF",
        green: "#4FE8B7",
        white: "#FEFEFF",
        "light-grey": "#F7F7F9",
        border: "#D9DBDE",
        grey: "#AEB1B7",
        "dark-grey": "#5D6470",
        black: "#15294A",
        error: "#FA1048",
        success: "#15CC8A",
        hoverRed: "#fa104814",
        pressedRed: "#fa10481f",
        design: "#FFE8E8",
        hr: "#D6E1FF",
        sales: "#F2E8FF",
        dev: "#D2FAEE",
        finance: "#FFF2D1",
        "team1": "#FFE8E8",
        "team2": "#D6E1FF",
        "team3": "#F2E8FF",
        "team4": "#D2FAEE",
        "team5": "#FFF2D1",
        "team6": "#E8F1FF",
        "team7": "#FFEBE8",
        "team8": "#E8FFF2",
        "team9": "#FFF8E8",
        "team10": "#F2D1FF",
        "team11": "#4260f5",
        "team12": "#E8FFD6",
        "team13": "#FFD1F2",
        "team14": "#D1FFE8",
        "team15": "#D6FFD6",
        "team16": "#FFD6D6",
        "team17": "#E8D1FF",
        "team18": "#D1F2FF",
        "team19": "#FFF2E8",
        "team20": "#FFE8D1",
        "team21": "#D1FFE1",
        "team22": "#F2D1E8",
        "team23": "#D6F2FF",
        "team24": "#FFF2FF",
        "team25": "#E8D1D1",
        lightGreen: "#AAF6CD",
        lightRed: "#FFC6D3",
        lightYellow: "#FFE9AF",
        lightPurple: "#ECDEFF",
        lightBlue: "#D8E7FF",
        lightBackgroundShop: "#FBFBFE",
        disabled: "#E1E4EA",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        loader: {
          "0%": { width: "0%" },
          "50%": { width: "50%" },
          "100%": { width: "100%" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        loader: "loader 1s  ease-in infinite",
      },
    },
  },
  plugins: [],
};
