export const INITIAL_MEMBER_DATA = {
  firstName: "",
  lastName: "",
  dateOfBirth: "",
  phone: "",
  email: "",
  team: "",
  jobPosition: "",
  zipCode: "",
  city: "",
  address: "",
  appartment: "",
  joiningDate: "",
  timeSlotForDelivery: "",
  additionalInfo: "",
};
